m1/config/routes.rb
Diablogger::Application.routes.draw do |map|

  root :to => "public#index", :via => "get"

  get "create/dialog", :to => 'dialogs#create', :as => "diablogs_create"
  post "create/dialog", :to => 'dialogs#create_submit', :as => "diablogs_create_submit"

end

m1/app/models/author.rb
class Author
  include DataMapper::Resource

  property :id, Integer, :key => true
  property :email, String, :format => :email_address, :unique => true, :length => (1..100), :messages => {
    :presence => "We need your email address.",
    :is_unique => "We've already got a registration for that email.",
    :format => "That doesn't look like an email address to me..."
  }
  property :pseudonym, String, :required => true, :length => (1..30)
  property :city, String # TODO geolocate primary login IP address and autofill city, state, country, postal
  property :state, String
  property :country, String
  property :postal, String
  property :created_at, DateTime
  property :updated_at, DateTime

  belongs_to :user, :child_key => :id, :required => true, :unique => true, :default => User.new

  has n, :posts
  has n, :diablogs, :through => :posts
  has n, :comments

  def to_json options
    if options[:methods]
      options[:methods] << :id
    else
      options[:methods] = [:id]
    end
    
    super options
  end
end

m1/app/models/comment.rb
class Comment
  include DataMapper::Resource

  belongs_to :post, :key => true, :required => true
  belongs_to :author, :key => true
  property :created_at, DateTime, :key => true
  property :updated_at, DateTime

end

m1/app/models/diablog.rb
class Diablog
  include DataMapper::Resource
  
  property :id, Serial
  property :subject, String, :required => true, :length => (5..1000)
  property :creator_id, Integer
  property :created_at, DateTime
  property :updated_at, DateTime

  belongs_to :creator, :model => 'Author', :required => true, :default => Author.new

  has n, :posts, :order => :created_at
  has n, :authors, :through => :posts

  accepts_nested_attributes_for :creator
  accepts_nested_attributes_for :posts
  accepts_nested_attributes_for :authors
end

m1/app/models/login_address.rb
class LoginAddress
  include DataMapper::Resource

  belongs_to :user, :required => true, :key => true
  property :ip, Integer, :key => true
  property :postal, String
  property :logins, Integer
  property :created_at, DateTime
  property :updated_at, DateTime
end

m1/app/models/post.rb
class Post
  include DataMapper::Resource

  property :author_id, Integer, :key => true
  property :diablog_id, Integer, :key => true
  property :created_at, DateTime, :key => true
  property :updated_at, DateTime
  property :up_votes, Integer
  property :down_votes, Integer
  property :body, Text, :lazy => false, :required => true

  belongs_to :author
  belongs_to :diablog

  has n, :comments, :order => :created_at

  validates_with_block :body do
    if body.split.size < 1000
      [true]
    else
      [false, "You've got too many words!  The limit is 1000." ]
    end
  end
end

m1/app/models/user.rb
class User
  include DataMapper::Resource

  property :id, Serial

  has n, :login_addresses
  has 1, :author, :child_key => :id, :default => lambda{ |user,author| Author.new :id => user.id, :user => user }

end

m1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def request_user
    User.get 1
  end
end

m1/app/controllers/dialogs_controller.rb
class DialogsController < ApplicationController
  def show
    @diablog = Diablog.get params[:id]
  end

  def create
    @diablog = Diablog.new :creator => request_user.author, :posts => [(Post.new :author => request_user.author)]
  end

  def create_submit
    @diablog = Diablog.new params[:diablog]
    if @diablog.save
      flash[:notice] = "woot"
      redirect_to root_url
    else
      flash.now[:error] = "oops"
      render :create
    end
  end

end

m1/app/controllers/public_controller.rb
class PublicController < ApplicationController
  layout 'public'
  
  def index
    @top_authors = Author.all :limit => 10
    @top_diablogs = Diablog.all :limit => 10
  end

end

m1/app/helpers/application_helper.rb
module ApplicationHelper
end

m1/app/helpers/public_helper.rb
module PublicHelper
end

m1/app/views/diablogs/create.html.erb
<%= form_for @diablog, :url => diablogs_create_submit_url do |diablog| %>
  <%= fields_for @diablog.creator do |creator| -%>
    <%= creator.label :email %>
    <%= creator.text_field :email %>
  <% end %>
  <%= diablog.label :subject %>
  <%= diablog.text_field :subject %>
  <%= fields_for @diablog.posts.first do |post| -%>
    <%= post.text_area :body %>
  <% end %>
  <%= diablog.submit 'Create' %>
<% end %>

m1/app/views/layouts/public-erb.html.erb
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="Description" content="Conversations for the record.  Free and simple diablog hosting." />
    <title><%= "#{@title.blank? ? '': "#{@title} | "}Diablogger" -%></title>
    <%= javascript_include_tag 'common', :cache => "common_cache" %>
    <%= javascript_include_tag "views/#{params[:controller]}" %>
    <%= stylesheet_link_tag 'common', :cache => "common_cache" %>
    <link rel="shortcut icon" href="/favicon.ico" />
  </head>
  <body id="body"></body>
  <%= yield %>
  <script type="text/javascript">
    window.onload = function(){
      document.getElementById('body').innerHTML = templates.layouts.public( templates.<%= params[:controller] %>.<%= params[:action] %>() );
    };
  </script>
</html>